server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: blockchain-traceability-demo

# 区块链配置
blockchain:
  # Ganache RPC 地址 (从环境变量读取，默认端口7545)
  rpc-url: ${BLOCKCHAIN_RPC_URL:http://127.0.0.1:7545}

  # 智能合约地址 (从环境变量读取，部署后需要填入)
  contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS:''}

  # 私钥 (从环境变量读取，不要在生产环境中硬编码)
  private-key: ${BLOCKCHAIN_PRIVATE_KEY:''}

# 日志配置
logging:
  level:
    org.linyi.test: DEBUG
    org.web3j: WARN
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
